// Mutation projects

export const UPDATE_PROJECTS = 'UPDATE_PROJECTS';
export const GENERATE_PROJECTS_TYPES = 'GENERATE_PROJECTS_TYPES';
export const ADD_NEW_PROJECT = 'ADD_NEW_PROJECT';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const CHANGE_OPEN_OPTIONS = 'CHANGE_OPEN_OPTIONS';
export const CHANGE_NAME_PROJECT = 'CHANGE_NAME_PROJECT';
export const ADD_PAGE = 'ADD_PAGE';
export const REMOVE_PAGE = 'REMOVE_PAGE';
// OTHER mutation types